# --- General ---
# Kitty reloads automatically when you save this file
# To include your theme file:
include ~/.config/kitty/themes/tokyo-night-kitty.conf


# --- Window ---
# Kitty handles decorations natively based on OS, but you can target it:
hide_window_decorations no
# 'Dark' variant is usually inherited by the OS theme automatically, 
# but you can force dark title bars on Linux/X11 with:
linux_display_server x11

# Kitty doesn't have a direct "Maximized" string flag like Alacritty, 
# so we start it with large dimensions to force maximization on launch:
remember_window_size  no
initial_width         100c
initial_height        100c
background_opacity    1.0

# --- Font ---
font_family      0xProto Nerd Font Mono
bold_font        auto
italic_font      auto
font_size        18.0

