[colors]
; Base
background     = #1a1b26
background-alt = #24283b

foreground     = #a9b1d6
disabled       = #565f89

; Accents
primary   = #7aa2f7
secondary = #bb9af7

; States
alert   = #f7768e
warning = #e0af68
success = #9ece6a
