# Retrobox colors for tmux
set -g status-style "bg=#282828,fg=#ebdbb2"
set -g message-style "bg=#504945,fg=#fe8019"

# Border colors
set -g pane-border-style "fg=#504945"
set -g pane-active-border-style "fg=#fe8019" # Retrobox signature orange

# Status bar items
set -g status-left "#[fg=#282828,bg=#fe8019,bold] #S "
set -g window-status-current-format "#[fg=#282828,bg=#fabd2f,bold] #I:#W "
set -g window-status-format "#[fg=#7c6f64,bg=#282828] #I:#W "
